openapi: 3.1.0
info:
  title: W3C Specifications API
  description: Retrieve W3C specifications filtered by keyword such as "accessibility".
  version: 1.0.0
servers:
  - url: https://api.w3.org
    description: W3C public API
paths:
  /specifications:
    get:
      operationId: getAccessibilitySpecifications
      summary: Get W3C specifications filtered by accessibility
      description: Returns a list of W3C specifications matching the keyword "accessibility".
      parameters:
        - name: apikey
          in: query
          required: true
          description: Your W3C API key
          schema:
            type: string
        - name: q
          in: query
          required: false
          description: Keyword to search specifications (e.g., "accessibility")
          schema:
            type: string
            default: accessibility
      responses:
        '200':
          description: A list of specifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  _links:
                    type: object
                  specifications:
                    type: array
                    items:
                      type: object
                      properties:
                        shortlink:
                          type: string
                        title:
                          type: string
                        status:
                          type: string
                        publisher:
                          type: string
